---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cdi
  namespace: cdi
spec:
  hosts:
    - cdi.bigbang.dev
  gateways:
    - istio-system/public
  http:
    - route:
        - destination:
            host: msr.msr.svc.cluster.local
            port:
              number: 8180
